site_name: Nextcloud Talk API documentation

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - php
    - js
    - bash

markdown_extensions:
  - admonition
  - def_list
  - toc:
      permalink: "#"
      baselevel: 2

nav:
  - 'Overview': 'index.md'
  - 'User documentation':
      - 'User system requirements': 'user-requirements.md'
  - 'Administration documentation':
      - 'Server system requirements': 'system-requirements.md'
      - 'Scalability': 'scalability.md'
      - 'Call experience': 'call-experience.md'
      - 'Occ commands': 'occ.md'
      - 'Bots': 'bot-list.md'
      - 'Commands (deprecated)': 'commands.md'
      - 'Matterbridge integration': 'matterbridge.md'
  - 'Developer documentation':
      - 'Bots and webhooks': 'bots.md'
      - 'Constants': 'constants.md'
      - 'Capabilities': 'capabilities.md'
      - 'PHP events': 'events.md'
  - 'API documentation':
      - 'Global API status and headers': 'global.md'
      - 'Conversations management': 'conversation.md'
      - 'Conversation avatars management': 'avatar.md'
      - 'Participants management': 'participant.md'
      - 'Call management': 'call.md'
      - 'Call recording management': 'recording.md'
      - 'Chat management': 'chat.md'
      - 'Reaction management': 'reaction.md'
      - 'Poll management': 'poll.md'
      - 'Breakout rooms management': 'breakout-rooms.md'
      - 'Bots management': 'bot-management.md'
      - 'Integration by other apps': 'integration.md'
      - 'Webinar management': 'webinar.md'
      - 'Settings': 'settings.md'
      - 'Signaling API': 'internal-signaling.md'
  - 'Configuring a TURN server':
      - 'Overview': 'TURN.md'
      - 'coTURN': 'coturn.md'
      - 'eturnal': 'eturnal.md'
  - 'Removed features':
      - 'Commands': 'commands.md'
