# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization

name: PHPUnit

on:
  pull_request:
    paths-ignore:
      - '.github/workflows/**'
      - 'appinfo/**'
      - 'lib/**'
      - 'templates/**'
      - 'tests/**'
      - 'vendor/**'
      - 'vendor-bin/**'
      - '.php-cs-fixer.dist.php'
      - 'composer.json'
      - 'composer.lock'

permissions:
  contents: read

jobs:
  summary-mysql:
    permissions:
      contents: none
    runs-on: ubuntu-latest

    name: phpunit-mysql-summary

    steps:
      - name: Summary status
        run: 'echo "No PHP files changed, skipped PHPUnit"'

  summary-oci:
    permissions:
      contents: none
    runs-on: ubuntu-latest

    name: phpunit-oci-summary

    steps:
      - name: Summary status
        run: 'echo "No PHP files changed, skipped PHPUnit"'

  summary-pgsql:
    permissions:
      contents: none
    runs-on: ubuntu-latest

    name: phpunit-pgsql-summary

    steps:
      - name: Summary status
        run: 'echo "No PHP files changed, skipped PHPUnit"'

  summary-sqlite:
    permissions:
      contents: none
    runs-on: ubuntu-latest

    name: phpunit-sqlite-summary

    steps:
      - name: Summary status
        run: 'echo "No PHP files changed, skipped PHPUnit"'
