# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization

name: Update nextcloud/ocp

on:
  workflow_dispatch:
  schedule:
    - cron: "5 2 * * 0"

jobs:
  update-nextcloud-ocp:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        branches: ["main", "master", "stable27", "stable26", "stable25"]

    name: update-nextcloud-ocp-${{ matrix.branches }}

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          ref: ${{ matrix.branches }}
          submodules: true

      - name: Set up php8.1
        uses: shivammathur/setup-php@4bd44f22a98a19e0950cbad5f31095157cc9621b # v2
        with:
          php-version: 8.1
          # https://docs.nextcloud.com/server/stable/admin_manual/installation/source_installation.html#prerequisites-for-manual-installation
          extensions: bz2, ctype, curl, dom, fileinfo, gd, iconv, intl, json, libxml, mbstring, openssl, pcntl, posix, session, simplexml, xmlreader, xmlwriter, zip, zlib, sqlite, pdo_sqlite
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Read codeowners
        id: codeowners
        run: |
          grep '/appinfo/info.xml' .github/CODEOWNERS | awk '{ print "codeowners="$2 }' >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Composer install
        run: composer install

      - name: Composer update nextcloud/ocp
        id: update_branch
        if: matrix.branches != 'main'
        run: composer require --dev nextcloud/ocp:dev-${{ matrix.branches }}

      - name: Raise on issue on failure
        uses: dacbd/create-issue-action@ba4d1c45cccf9c483f2720cefb40e437f0ee6f7d # v1.2.1
        if: ${{ failure() && steps.update_branch.conclusion == 'failure' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Failed to update nextcloud/ocp package on branch ${{ matrix.branches }}
          body: Please check the output of the GitHub action and manually resolve the issues<br>${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}<br>${{ steps.codeowners.outputs.codeowners }}

      - name: Composer update nextcloud/ocp
        id: update_main
        if: matrix.branches == 'main'
        run: composer require --dev nextcloud/ocp:dev-master

      - name: Raise on issue on failure
        uses: dacbd/create-issue-action@ba4d1c45cccf9c483f2720cefb40e437f0ee6f7d # v1.2.1
        if: ${{ failure() && steps.update_main.conclusion == 'failure' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Failed to update nextcloud/ocp package on branch ${{ matrix.branches }}
          body: Please check the output of the GitHub action and manually resolve the issues<br>${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}<br>${{ steps.codeowners.outputs.codeowners }}

      - name: Reset checkout 3rdparty
        run: |
          git clean -f 3rdparty
          git checkout 3rdparty
        continue-on-error: true

      - name: Reset checkout vendor
        run: |
          git clean -f vendor
          git checkout vendor
        continue-on-error: true

      - name: Reset checkout vendor-bin
        run: |
          git clean -f vendor-bin
          git checkout vendor-bin
        continue-on-error: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v3
        with:
          token: ${{ secrets.COMMAND_BOT_PAT }}
          commit-message: "chore(dev-deps): Bump nextcloud/ocp package"
          committer: GitHub <noreply@github.com>
          author: nextcloud-command <nextcloud-command@users.noreply.github.com>
          signoff: true
          branch: automated/noid/${{ matrix.branches }}-update-nextcloud-ocp
          title: "[${{ matrix.branches }}] Update nextcloud/ocp dependency"
          body: |
            Auto-generated update of [nextcloud/ocp](https://github.com/nextcloud-deps/ocp/) dependency
          labels: |
            dependencies
            3. to review
